"use strict";
const CAR_ID="car-r230-wdb2304671f117847";
const CAR={vin:"WDB2304671F117847",engine:"M112.973",gearbox:"722.644",name:"Mercedes-Benz SL 350 R230"};
const DEFAULT_MILEAGE=128000;
document.body.dataset.theme=new URLSearchParams(location.search).get("theme")||"graphite";
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const km=v=>Number(v)?Number(v).toLocaleString("ru-RU")+" км":"не указан";
const money=v=>Number(v)?Number(v).toLocaleString("ru-RU")+" ₽":"0 ₽";
function ruDate(v){let s=String(v||"");let m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?m[3]+"."+m[2]+"."+m[1]:(s||"дата не указана")}
const storeKey="r230-mvp-state-v3";
let S=JSON.parse(localStorage.getItem(storeKey)||'{"garage":{},"maintenance":{},"purchases":[]}');
let path=[{id:"node-root",name:"Главная"}], nodesCache={}, partsCache={};
let catalogItems=[],catalogZone="";
const zones=[["hood","Двигатель","мотор","двиг|охлаж|радиатор|топлив|впуск|выпуск|насос|рем|агрегат"],["trans","КП","привод","кп|автомат|кардан|педал|регулир|переключ"],["brake","Тормоза","диски","торм|brake"],["chassis","Ходовая","оси, колеса","подвес|пруж|мост|колес|колё|рулев|гидрав|вакуум"],["body","Кузов","салон","кузов|двер|крыш|боков|навес|лист|облицов|шасси|обшив|сиден"],["roof","Крыша","стекла","крыша|окна|стекл"],["electric","Электрика","жгуты","эл|жгут|контроль|прибор|обогрев|вентиляц"],["misc","Опции","прочее","инструмент|принадлеж|доп|специаль"]],jobs=[["помпа","Охлаждение"],["ремень ролик","Ремни"],["свечи","Свечи"],["тормозной диск","Тормоза"],["фильтр","Фильтры"],["радиатор","Радиатор"]];
const maint=[
["engineOil","Масло двигателя и масляный фильтр",10000,"Масло"],["transmissionOil","Масло АКПП",60000,"Масло"],["brakeFluid","Тормозная жидкость",0,"Жидкости"],["coolant","Антифриз",0,"Жидкости"],["powerSteering","ГУР / ABC",40000,"Жидкости"],["airFilter","Воздушный фильтр",20000,"Фильтры"],["cabinFilter","Салонный фильтр",15000,"Фильтры"],["sparkPlugs","Свечи зажигания",60000,"Зажигание"]
];
let mSelected=new Set(["engineOil"]);
function save(){localStorage.setItem(storeKey,JSON.stringify(S))}
function normalizeState(){S.garage=S.garage||{};S.maintenance=S.maintenance||{};S.purchases=Array.isArray(S.purchases)?S.purchases:[];let max=DEFAULT_MILEAGE;Object.values(S.maintenance).forEach(r=>{let n=Number(r&&r.mileage)||0;if(n>max)max=n});S.purchases.forEach(p=>{let n=p&&p.status==="Установлено"?(Number(p.mileage)||0):0;if(n>max)max=n});let cur=Number(S.garage.mileage)||0;if(cur<max){S.garage.mileage=String(max);save()}}
function updateMileage(v){let n=Number(v)||0,cur=Number(S.garage.mileage)||0;if(n&&n>=cur){S.garage.mileage=String(n);return true}return false}
async function data(p){let r=await fetch(p,{cache:"force-cache"});if(r.status===404)return {items:[]};if(!r.ok)throw Error(r.status);return r.json()}
function catalogKey(id){let v=String(id||"node-root"),h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function plural(n,a,b,c){n=Math.abs(Number(n)||0);let m=n%100,l=n%10;return n+" "+(m>10&&m<20?c:l===1?a:l>1&&l<5?b:c)}
const views=["home","search","catalog","maintenance","garage"];
let currentView="";
function view(name){name=views.includes(name)?name:"home";let prev=currentView||location.hash.slice(1);currentView=name;document.querySelectorAll("[data-view]").forEach(e=>e.classList.toggle("hidden",e.dataset.view!==name));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.open===name));if(location.hash.slice(1)!==name)location.hash=name;if(prev!==name)window.scrollTo(0,0);if(name==="garage")renderGarage();if(name==="maintenance")renderMaintenance();if(name==="catalog")renderCatalog();if(name==="search")$("q").focus()}
function renderHome(){ $("homeInfo").innerHTML='<div class="line"><span>VIN</span><b>'+CAR.vin+'</b></div><div class="line"><span>Двигатель</span><b>'+CAR.engine+'</b></div><div class="line"><span>КПП</span><b>'+CAR.gearbox+'</b></div><div class="line"><span>Пробег</span><b>'+km(S.garage.mileage)+'</b></div>'}
function totalSpend(){return (S.purchases||[]).reduce((sum,p)=>sum+(Number(p&&p.price)||0),0)}
function renderGarage(){renderHome();$("vin").value=CAR.vin;$("mileage").value=S.garage.mileage||"";let cards=$("vin").closest(".cards");[...cards.querySelectorAll(".card")].forEach(c=>{let t=c.innerText;if(t.includes("Двигатель")||t.includes("КПП"))c.remove()});if(!$("spendTotal"))cards.insertAdjacentHTML("beforeend",'<div class="card"><small>Общая сумма трат</small><b id="spendTotal">0 ₽</b><div class="muted">Запчасти и ремонт</div></div>');$("spendTotal").textContent=money(totalSpend());renderPurchases()}
function renderPurchases(){let a=S.purchases||[];if($("spendTotal"))$("spendTotal").textContent=money(totalSpend());$("purchaseCount").textContent=plural(a.length,"запись","записи","записей");$("purchases").innerHTML=a.length?a.map((p,i)=>'<div class="item"><b>'+esc(p.name||"Запчасть")+'</b><span class="part">'+esc(p.num||"номер не указан")+'</span><div class="status">'+esc(p.status||"Куплено")+' · '+esc(ruDate(p.date))+' · '+km(p.mileage)+(p.price?' · '+money(p.price):'')+'</div><div class="muted">'+esc(p.node||"узел не найден")+'</div><div class="purchase-edit"><select data-pstat="'+i+'"><option '+(p.status==="Куплено"?"selected":"")+'>Куплено</option><option '+(p.status==="Установлено"?"selected":"")+'>Установлено</option><option '+(p.status==="В запасе"?"selected":"")+'>В запасе</option></select><button class="btn" data-del="'+i+'">Удалить</button></div></div>').join(""):'<div class="status">Покупок пока нет.</div>';document.querySelectorAll("[data-pstat]").forEach(b=>b.onchange=()=>{let p=S.purchases[+b.dataset.pstat];p.status=b.value;if(p.status==="Установлено"&&p.mileage)updateMileage(p.mileage);save();renderGarage();toast("Статус обновлен")});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{S.purchases.splice(+b.dataset.del,1);save();renderGarage()})}
function cleanText(v,n){return String(v||"").replace(/[\u0000-\u001F\u007F]/g," ").replace(/\s+/g," ").trim().slice(0,n)}
function clip(v,n){return cleanText(v,n)}
function cleanPartNumber(v){return String(v||"").toUpperCase().replace(/[^A-ZА-Я0-9 .\/-]/g,"").replace(/\s+/g," ").trim().slice(0,32)}
function cleanDate(v){let s=String(v||"").trim();return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:""}
function cleanDigits(v,max){let s=String(v||"").replace(/\D/g,"");if(!s)return"";let n=Math.min(Number(s),max);return Number.isFinite(n)?String(Math.trunc(n)):""}
function numField(id,max){let value=cleanDigits($(id).value,max);$(id).value=value;return value}
function addPurchase(){let p={num:cleanPartNumber($("pnum").value),name:cleanText($("pname").value,80),status:$("pstatus").value,date:cleanDate($("pdate").value),mileage:numField("pmileage",999999),price:numField("pprice",99999999),node:cleanText($("pnode").value,80)};if(!p.num||!p.name)return toast("Укажи артикул и название");if(p.status==="Установлено"&&(!p.date||!p.mileage))return toast("Для установки нужны дата и пробег");S.purchases.unshift(p);if(p.status==="Установлено"&&updateMileage(p.mileage)){$("mileage").value=S.garage.mileage}save();["pnum","pname","pdate","pmileage","pprice","pnode"].forEach(id=>$(id).value="");renderGarage();toast("Запчасть сохранена");setTimeout(()=>$("purchases").scrollIntoView({block:"start",behavior:"smooth"}),60)}
function serviceStatus(m){let cur=Number(S.garage.mileage)||0,r=S.maintenance[m[0]]||{},last=Number(r.mileage)||0,has=!!(last||r.date||r.note);if(!m[2])return{r,next:0,left:0,progress:has?100:0,text:has?"записано":"нет данных"};let next=last?last+m[2]:0,left=next&&cur?next-cur:0,remaining=last&&cur?Math.min(100,Math.max(0,(left/m[2])*100)):0;return{r,next,left,progress:remaining,text:next?(cur?(left<=0?"сейчас":"через "+km(left)):"следующее "+km(next)):"нет данных"}}
function toggleService(id){if(mSelected.has(id)&&mSelected.size>1)mSelected.delete(id);else mSelected.add(id);renderMaintenance()}
function renderMaintenance(){if(!mSelected.size)mSelected.add("engineOil");let cur=Number(S.garage.mileage)||0,filled=maint.filter(m=>{let r=S.maintenance[m[0]]||{};return r.mileage||r.date||r.note}).length,withNext=maint.map(m=>({m,s:serviceStatus(m)})).filter(x=>x.s.next),next=withNext.sort((a,b)=>a.s.left-b.s.left)[0]||{m:maint[0],s:{text:"нет данных",progress:0}},due=withNext.filter(x=>x.s.left<=0).length;$("maintenanceSummary").innerHTML='<div class="service-tile light"><div><b>'+km(cur)+'</b><small>Ваш последний пробег</small></div><button class="btn update-mini" data-open="garage">Обновить</button></div><div class="service-tile dark"><small>Следующее ТО · '+esc(next.m[1])+'</small><b>'+esc(next.s.text)+'</b><div class="progress"><span style="width:'+esc(next.s.progress)+'%"></span></div><small>'+filled+' из '+maint.length+' заполнено · требуют внимания: '+due+'</small></div>';$("maintenanceProgress").textContent=filled+"/"+maint.length+" заполнено";$("mtitle").textContent="Комплексное ТО";$("mchecks").innerHTML=maint.map(m=>'<label class="service-check '+(mSelected.has(m[0])?'active':'')+'"><input type="checkbox" data-mcheck="'+m[0]+'" '+(mSelected.has(m[0])?'checked':'')+'><span>'+esc(m[1])+'</span><small>'+esc(m[3])+'</small></label>').join("");$("maintenanceCards").innerHTML=maint.map(m=>{let s=serviceStatus(m),r=s.r;return '<button class="service-card '+(mSelected.has(m[0])?'active':'')+'" data-mid="'+m[0]+'"><div class="service-card-title"><b>'+esc(m[1])+'</b><span class="service-tag">'+esc(m[3])+'</span></div><div class="service-mini light"><b>'+km(r.mileage)+'</b><small>последнее обслуживание</small><span>'+esc(ruDate(r.date))+'</span></div><div class="service-mini dark"><small>Следующее ТО</small><b>'+esc(s.text)+'</b><div class="progress"><span style="width:'+esc(s.progress)+'%"></span></div></div></button>'}).join("");document.querySelectorAll("[data-mcheck]").forEach(c=>c.onchange=()=>{if(c.checked)mSelected.add(c.dataset.mcheck);else if(mSelected.size>1)mSelected.delete(c.dataset.mcheck);else c.checked=true;renderMaintenance()});document.querySelectorAll("[data-mid]").forEach(b=>b.onclick=()=>toggleService(b.dataset.mid))}
function saveMaintenance(){let ids=[...mSelected];if(!ids.length)return toast("Выбери работы ТО");let r={date:cleanDate($("mdate").value),mileage:numField("mmileage",999999),note:cleanText($("mnote").value,160)};$("mdate").value=r.date;$("mnote").value=r.note;if(!r.date||!r.mileage)return toast("Заполни дату и пробег");ids.forEach(id=>{S.maintenance[id]={...r}});updateMileage(r.mileage);save();renderMaintenance();renderHome();toast("ТО сохранено: "+ids.length)}
async function loadNodes(id){if(nodesCache[id])return nodesCache[id];let d=await data("catalog/nodes/"+catalogKey(id)+".json");return nodesCache[id]=d.items||[]}
async function loadParts(id){if(partsCache[id])return partsCache[id];let d=await data("catalog/parts/"+catalogKey(id)+".json");return partsCache[id]=d.items||[]}
function partExtra(p,showImage=true){let img=showImage&&p.imageUrl?'<img class="part-img" src="'+esc(p.imageUrl)+'" loading="lazy" alt="">':"",d=String(p.description||""),long=d.length>130,desc=d?'<div class="muted desc '+(long?'desc-cut':'')+'">'+esc(d)+'</div>'+(long?'<button class="desc-toggle">Показать полностью</button>':""):"";return img+desc}
function nodePartCount(n){return Number(n&&((n.totalPartCount||0)||(n.partCount||0)))||0}
function nodeStatusText(n){let c=Number(n&&n.childCount)||0,p=nodePartCount(n),kind=n&&n.childKind==="scheme";return c?plural(c,kind?"схема":"раздел",kind?"схемы":"раздела",kind?"схем":"разделов")+" · "+plural(p,"деталь","детали","деталей"):plural(p,"деталь","детали","деталей")}
function nodeDiagram(n){let count=nodePartCount(n);return n&&n.imageUrl?'<section class="catalog-diagram image-pending"><img src="'+esc(n.imageUrl)+'" loading="lazy" alt="Схема '+esc(n.name||"узла")+'" onload="this.closest(\'.catalog-diagram\').classList.remove(\'image-pending\')" onerror="let d=this.closest(\'.catalog-diagram\');d.classList.remove(\'image-pending\');d.classList.add(\'image-missing\')"><div class="diagram-pending"><b>Загружаю схему</b><span>Проверяю файл схемы для этого узла.</span></div><div class="diagram-fallback"><b>Схема не загрузилась</b><span>Файл каталога недоступен. Номера деталей ниже можно использовать.</span></div><div class="diagram-caption"><b>'+esc(n.name||"Схема узла")+'</b><span>'+plural(count,"деталь","детали","деталей")+'</span></div></section>':""}
function isLocalImage(u){return !!u&&!/^https?:\/\//i.test(String(u))}
function nodeCard(n,showThumb){let preview=isLocalImage(n.previewImageUrl)?n.previewImageUrl:"";let img=showThumb&&preview?'<img class="node-thumb" loading="lazy" src="'+esc(preview)+'" alt="Схема '+esc(n.name)+'">':"";return '<button class="item node-card '+(img?'':'no-thumb')+'" data-node="'+esc(n.id)+'">'+img+'<span><b>'+esc(n.name)+'</b><div class="status">'+esc(nodeStatusText(n))+'</div></span></button>'}
function partRow(x,i){let p=x.part||{},u=x.usage||{},pos=u.positionLabel||p.positionCode||"-";return '<div class="item part-row"><div class="pos">'+esc(pos)+'</div><div><b>'+esc(p.name)+'</b><span class="part">'+esc(p.partNumber)+'</span><div class="status">кол-во '+esc(u.quantity||1)+' · '+esc(path[path.length-1].name)+'</div><div class="part-actions"><button class="btn" data-copy-part="'+i+'">Копировать</button><button class="btn primary" data-add-part="'+i+'">В гараж</button></div></div></div>'}
function renderCatalogHome(nodes){let z=zones.find(x=>x[0]===catalogZone),filtered=z?nodes.filter(n=>new RegExp(z[3],"i").test(n.name)):[];return '<div class="catalog-hero"><input id="catalogQ" type="search" placeholder="Поиск"><button class="btn primary" id="catalogSearchBtn">Искать</button></div><div class="catalog-section"><h3>Зоны</h3><div class="catalog-zone-grid">'+zones.map(z=>'<button class="catalog-zone" data-zone="'+z[0]+'"><b>'+z[1]+'</b><small>'+z[2]+'</small></button>').join("")+'</div></div><div class="catalog-section"><h3>Работы</h3><div class="catalog-chips">'+jobs.map(j=>'<button class="catalog-chip" data-cq="'+esc(j[0])+'">'+esc(j[1])+'</button>').join("")+'</div></div>'+(z?'<div class="catalog-list-title"><h3>'+z[1]+'</h3><button class="btn" data-zone="">Закрыть</button></div>'+(filtered.map(n=>nodeCard(n,false)).join("")||'<div class="status">Нет групп.</div>'):'<div class="status">Выбери зону.</div>')}
function addCatalogPart(i){let x=catalogItems[i]||{},p=x.part||{};view("garage");setTimeout(()=>{$("pnum").value=p.partNumber||"";$("pname").value=p.name||"";$("pnode").value=x.node&&x.node.name||path.at(-1).name||"";toast("Заполни дату и цену")})}
function wireCatalog(){let q=$("catalogQ"),body=$("catalogBody");if(q){$("catalogSearchBtn").onclick=()=>{view("search");$("q").value=q.value;search()};q.onkeydown=e=>{if(e.key==="Enter")$("catalogSearchBtn").click()}}body.onclick=e=>{let b=e.target.closest("[data-node],[data-zone],[data-cq],[data-copy-part],[data-add-part]");if(!b)return;if(b.dataset.node){let n=catalogItems.find(x=>x.id===b.dataset.node);path.push(n);catalogZone="";renderCatalog()}else if("zone"in b.dataset){catalogZone=b.dataset.zone;path=[{id:"node-root",name:"Главная"}];renderCatalog()}else if(b.dataset.cq){view("search");$("q").value=b.dataset.cq;search()}else if("copyPart"in b.dataset){let p=(catalogItems[+b.dataset.copyPart]||{}).part||{};navigator.clipboard&&navigator.clipboard.writeText(p.partNumber||"");toast("Номер скопирован")}else addCatalogPart(+b.dataset.addPart)}}
async function renderCatalog(){let cur=path[path.length-1];$("crumbs").innerHTML=path.length>1?'<button class="btn" data-back>‹ Назад</button>':"";let bb=document.querySelector("[data-back]");if(bb)bb.onclick=()=>{path.pop();catalogZone="";renderCatalog()};$("catalogBody").innerHTML='<div class="status">Загружаю...</div>';try{let parts=cur.id==="node-root"?[]:await loadParts(cur.id),nodes=(parts.length?[]:await loadNodes(cur.id)).filter(n=>nodePartCount(n)>0);catalogItems=parts.length?parts:nodes;let top=parts.length?nodeDiagram(cur):"",showThumbs=cur.id!=="node-root";if(cur.id!=="node-root"&&!parts.length&&!nodes.length){path=[{id:"node-root",name:"Главная"}];return renderCatalog()}$("catalogBody").innerHTML=cur.id==="node-root"?renderCatalogHome(nodes):top+(nodes.map(n=>nodeCard(n,showThumbs)).join("")||"")+(parts.length?'<div class="catalog-list-title"><h3>Детали на схеме</h3><span class="tag">'+plural(parts.length,"деталь","детали","деталей")+'</span></div>'+parts.map(partRow).join(""):(!nodes.length?'<div class="status">В этом узле пока нет строк.</div>':""));document.querySelectorAll(".catalog-diagram.image-pending").forEach(d=>setTimeout(()=>{let img=d.querySelector("img");if(img&&(!img.complete||!img.naturalWidth)){d.classList.remove("image-pending");d.classList.add("image-missing")}},4500));wireCatalog()}catch(e){if(cur.id!=="node-root"){path=[{id:"node-root",name:"Главная"}];return renderCatalog()}$("catalogBody").innerHTML='<div class="status">Не удалось загрузить каталог. Попробуй еще раз.</div>'}}
let searchCache=null;
function norm(v){return String(v||"").toLowerCase().replace(/ё/g,"е").replace(/[^a-zа-я0-9]/gi,"")}
function normPart(v){return String(v||"").toUpperCase().replace(/[^A-ZА-Я0-9]/g,"")}
function expandQuery(q){let a=[q],m={помпа:["насос"],насос:["помпа"],свеч:["свеча","зажиг"],тормоз:["brake","колодки"],колодки:["тормоз"],ремень:["ролик"],ролик:["ремень"],фильтр:["filter"],filtr:["фильтр"],filter:["фильтр"],радиатор:["охлаждение"]};Object.keys(m).forEach(k=>{if(q.includes(k))a.push(...m[k])});return [...new Set(a.filter(x=>x&&x.length>1))]}
async function ensureSearch(){if(!searchCache)searchCache=(await data("catalog/search.json")).items||[];return searchCache}
async function search(){let raw=$("q").value.trim(),q=norm(raw);if(!q){view("catalog");return}if(q.length<2){$("results").innerHTML='<div class="status">Введите минимум 2 символа.</div>';return}$("results").innerHTML='<div class="status">Ищу</div>';try{let cache=await ensureSearch(),queries=expandQuery(q);let items=cache.map(x=>{let hay=norm((x.part&&x.part.name||"")+" "+(x.part&&x.part.partNumber||"")+" "+(x.node&&x.node.name||"")),score=queries.reduce((s,v)=>s+(hay.includes(v)?(v===q?3:2):0),0);return{x,score}}).filter(r=>r.score).sort((a,b)=>b.score-a.score).slice(0,30).map(r=>r.x);catalogItems=items;$("results").innerHTML=items.map((x,i)=>'<div class="item"><b>'+esc(x.part.name)+'</b><span class="part">'+esc(x.part.partNumber)+'</span>'+partExtra(x.part||{})+'<div class="status">'+esc(x.node&&x.node.name||"")+'</div><div class="part-actions"><button class="btn" data-copy-part="'+i+'">Копировать</button><button class="btn primary" data-add-part="'+i+'">В гараж</button></div></div>').join("")||'<div class="status">Нет результатов.</div>'}catch(e){$("results").innerHTML='<div class="status">Поиск временно недоступен.</div>'}}
async function autoFillPurchase(){let raw=$("pnum").value.trim();if(raw.length<5)return;try{let part=normPart(raw),items=await ensureSearch(),hit=items.find(x=>normPart(x.part&&x.part.partNumber)===part)||items.find(x=>normPart(x.part&&x.part.partNumber).includes(part));if(hit){$("pname").value=hit.part.name||"";$("pnode").value=hit.node&&hit.node.name||""}else{$("pnode").value=""}}catch(e){}}
function renderCalendar(el){el.focus()}
function wireDatePicker(id){let el=$(id);if(!el)return;let open=()=>{if(typeof el.showPicker==="function"){try{el.showPicker();return}catch{}}renderCalendar(el)};el.addEventListener("pointerdown",open);el.addEventListener("click",open);el.addEventListener("keydown",e=>{if(e.key===" "||e.key==="Enter"){e.preventDefault();open()}})}
function wireValidation(){["mdate","pdate"].forEach(id=>{let el=$(id);if(el){el.min="2001-01-01";el.max="2100-12-31"}wireDatePicker(id)});[["mileage",999999],["mmileage",999999],["pmileage",999999],["pprice",99999999]].forEach(([id,max])=>{let el=$(id);if(el){el.min="0";el.max=String(max);el.step="1";el.inputMode="numeric";el.oninput=()=>{el.value=cleanDigits(el.value,max)}}});let pnum=$("pnum");if(pnum){pnum.autocomplete="off";pnum.autocapitalize="characters";pnum.spellcheck=false;pnum.pattern="[A-Za-zА-Яа-я0-9 ./-]{1,32}";pnum.oninput=()=>{pnum.value=cleanPartNumber(pnum.value);clearTimeout(window.pt);window.pt=setTimeout(autoFillPurchase,220)}}[["pname",80],["mnote",160]].forEach(([id,max])=>{let el=$(id);if(el)el.onblur=()=>{el.value=cleanText(el.value,max)}})}
document.addEventListener("click",e=>{let d=e.target.closest(".desc-toggle");if(d){let x=d.previousElementSibling;x.classList.toggle("desc-cut");d.textContent=x.classList.contains("desc-cut")?"Показать полностью":"Свернуть";return}let p=e.target.closest("[data-copy-part],[data-add-part]");if(p&&!p.closest("#catalogBody")){if("copyPart"in p.dataset){let x=(catalogItems[+p.dataset.copyPart]||{}).part||{};navigator.clipboard&&navigator.clipboard.writeText(x.partNumber||"");toast("Номер скопирован")}else addCatalogPart(+p.dataset.addPart);return}let b=e.target.closest("[data-open]");if(b)view(b.dataset.open)});
wireValidation();$("mileage").oninput=()=>{S.garage.mileage=cleanDigits($("mileage").value,999999);$("mileage").value=S.garage.mileage;save();renderHome()};$("copyVin").onclick=()=>navigator.clipboard?navigator.clipboard.writeText(CAR.vin).then(()=>toast("VIN скопирован")):toast(CAR.vin);$("savePurchase").onclick=addPurchase;$("saveM").onclick=saveMaintenance;$("q").oninput=()=>{clearTimeout(window.t);window.t=setTimeout(search,220)};$("q").onsearch=search;
window.addEventListener("hashchange",()=>{let h=(location.hash||"#home").slice(1);if(h!==currentView)view(h)});
normalizeState();renderHome();let initial=(location.hash||"#home").slice(1);view(views.includes(initial)?initial:"home");