/*-----------------------------------------------------------------------------
This page was automatically generated by WebETMCreate.php
on Sep-12-2006 6:28:35
Created by RLE International GmbH
Copyright 2006 Mercedes-Benz USA, LLC
-----------------------------------------------------------------------------*/
var groupA = new Array();
function groupItem(description, diagramA)
{
	this.description = description;
	this.diagramA = diagramA;
}

var diagramA = new Array();
function diagramItem(description, annotations, modelyear, engine)
{
	this.description = description;
	this.annotations = annotations;
	this.modelyear = modelyear;
	this.engine = engine;
}



diagramA["PE00.19-U-2200KA"] = new diagramItem("Engine CAN bus",
  "MODEL 230 with ENGINE<BR>   113.963 /992, 275.951 up to 02/28/06, <BR>275.981, <BR>113.995, 275.954, 273 as of 03/01/06",
  "",
  "");

diagramA["PE00.19-U-2300KA"] = new diagramItem("Interior CAN bus",
  "MODEL 230 up to 05/31/02<BR>sheet 1, CAN voltage distributor (X30/15)",
  "",
  "");

diagramA["PE00.19-U-2300KB"] = new diagramItem("Interior CAN bus",
  "MODEL 230 up to 05/31/02<BR>sheet 2, CAN voltage distributor (X30/17)",
  "",
  "");

diagramA["PE00.19-U-2300KC"] = new diagramItem("Interior CAN bus",
  "MODEL 230 up to 05/31/02<BR>sheet 3, CAN voltage distributor (X30/16)",
  "",
  "");

diagramA["PE00.19-U-2300KD"] = new diagramItem("Interior CAN bus",
  "MODEL 230 as of 06/01/02 up to 08/31/03<BR>sheet 1, CAN voltage distributor (X30/15)",
  "",
  "");

diagramA["PE00.19-U-2300KE"] = new diagramItem("Interior CAN bus",
  "MODEL 230 as of 06/01/02 up to 08/31/03<BR>sheet 2, CAN voltage distributor (X30/17)",
  "",
  "");

diagramA["PE00.19-U-2300KF"] = new diagramItem("Interior CAN bus",
  "MODEL 230 as of 06/01/02 up to 08/31/03<BR>sheet 3, CAN voltage distributor (X30/16)",
  "",
  "");

diagramA["PE00.19-U-2300KG"] = new diagramItem("Interior CAN bus",
  "MODEL 230 as of 09/01/03<BR>sheet 1, CAN voltage distributor (X30/15)",
  "",
  "");

diagramA["PE00.19-U-2300KH"] = new diagramItem("Interior CAN bus",
  "MODEL 230 as of 09/01/03<BR>sheet 2, CAN voltage distributor (X30/17)",
  "",
  "");

diagramA["PE00.19-U-2300KI"] = new diagramItem("Interior CAN bus",
  "MODEL 230 as of 09/01/03<BR>sheet 3, CAN voltage distributor (X30/16)",
  "",
  "");

diagramA["PE00.19-U-2800KA"] = new diagramItem("Ground wiring",
  "MODEL 230<BR>W3/1, W3/2, W6, W6/1, W7, W10/3, W11/3, W15, W15/3, <BR>Sheet 1",
  "",
  "");

diagramA["PE00.19-U-2800KB"] = new diagramItem("Ground wiring",
  "MODEL 230<BR>W26, W30, W34/1, W34/2, <BR>Sheet 2",
  "",
  "");

diagramA["PE00.19-U-2800KC"] = new diagramItem("Ground wiring",
  "MODEL 230<BR>W36, W37, <BR>Sheet 3",
  "",
  "");

// 13
groupA["00"] = new groupItem("Multi-function Circuits", diagramA);
var diagramA = new Array();

diagramA["PE07.61-U-2050KA"] = new diagramItem("Function diagram of electrical system for ME engine control",
  "ENGINE 113.963 up to 02/28/06 in MODEL 230<BR>ME 2.8",
  "",
  "");

diagramA["PE07.61-U-2050KB"] = new diagramItem("Function diagram of electrical system for ME engine control",
  "ENGINE 113.992 up to 02/28/06, <BR>113.995 as of 03/01/06<BR>in MODEL 230<BR>ME 2.8.1",
  "",
  "");

diagramA["PE07.61-U-2050KC"] = new diagramItem("Function diagram of electrical system for ME engine control",
  "ENGINE 275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981<BR>in MODEL 230<BR>ME 2.7.1",
  "",
  "");

diagramA["PE07.61-U-2050KD"] = new diagramItem("Function diagram of electrical system for ME engine control",
  "ENGINE 273 as of 03/01/06 in MODEL 230<BR>ME9.7",
  "",
  "");

diagramA["PE07.61-U-2101KA"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 113.963 up to 02/28/06 in MODEL 230<BR>(Version ME 2.8), <BR>Sheet 1",
  "",
  "");

diagramA["PE07.61-U-2101KB"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 113.963 /992 up to 02/28/06, <BR>113.995 as of 03/01/06<BR>in MODEL 230<BR>(Version ME 2.8 / ME 2.8.1), <BR>Sheet 2",
  "",
  "");

diagramA["PE07.61-U-2101KC"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981<BR>in MODEL 230<BR>(Version ME 2.7.1), <BR>Sheet 1",
  "",
  "");

diagramA["PE07.61-U-2101KD"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981<BR>in MODEL 230<BR>(Version ME 2.7.1), <BR>Sheet 2",
  "",
  "");

diagramA["PE07.61-U-2101KE"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981<BR>in MODEL 230<BR>(Version ME 2.7.1), <BR>Sheet 3",
  "",
  "");

diagramA["PE07.61-U-2101KF"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 113.992 up to 02/28/06, <BR>113.995 as of 03/01/06<BR>in MODEL 230<BR>(Version ME 2.8.1), <BR>Sheet 1",
  "",
  "");

diagramA["PE07.61-U-2101KG"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 273 as of 03/01/06 in MODEL 230<BR>ME 9.7, <BR>sheet 1",
  "",
  "");

diagramA["PE07.61-U-2101KI"] = new diagramItem("ME-SFI fuel injection and ignition system, control module",
  "ENGINE 273 as of 03/01/06 in MODEL 230<BR>ME 9.7, <BR>sheet 2",
  "",
  "");

// 12
groupA["07"] = new groupItem("Engine - Fuel Management", diagramA);
var diagramA = new Array();

diagramA["PE15.00-U-2050KA"] = new diagramItem("Electrical function diagram for starter, alternator, battery",
  "ENGINE 113.963 /992 up to 02/28/06, <BR>113.995 as of 03/01/06<BR>in MODEL 230",
  "",
  "");

diagramA["PE15.00-U-2050KB"] = new diagramItem("Electrical function diagram for starter, alternator, battery",
  "ENGINE 275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981<BR>in MODEL 230",
  "",
  "");

diagramA["PE15.00-U-2050KC"] = new diagramItem("Electrical function diagram for starter, alternator, battery",
  "ENGINE 273 as of 03/01/06 in MODEL 230",
  "",
  "");

// 3
groupA["15"] = new groupItem("Engine - Electrical", diagramA);
var diagramA = new Array();

diagramA["PE27.19-U-2050KA"] = new diagramItem("Function diagram of electrical system for electronic transmission control (ETC)",
  "TRANSMISSION 722.6 in MODEL 230<BR>with ENGINE 113.963 up to 08/31/03, <BR>113.992 up to 02/28/06, <BR>113.995 as of 03/01/06, <BR>275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981",
  "",
  "");

diagramA["PE27.19-U-2050KB"] = new diagramItem("Function diagram of electrical system for electronic transmission control (ETC)",
  "TRANSMISSION 722.9 as of 09/01/03 in MODEL 230<BR>with ENGINE 113.963 up to 02/28/06, <BR>273 as of 03/01/06",
  "",
  "");

diagramA["PE27.19-U-2101KA"] = new diagramItem("Electronic transmission control (ETC) control module",
  "TRANSMISSION 722.6 in MODEL 230<BR>with ENGINE 113.963 /992 up to 02/28/06, <BR>113.995 as of 03/01/06, <BR>275.951 up to 02/28/06, <BR>275.981, <BR>275.954 as of 03/01/06 with CODE (423) Automatic five-speed transmission (NAG)",
  "",
  "");

diagramA["PE27.19-U-2101KB"] = new diagramItem("Electronic transmission control (ETC) control module",
  "TRANSMISSION 722.9 as of 09/01/03 in MODEL 230<BR>with ENGINE 113.963 up to 02/28/06, <BR>273 as of 03/01/06 with CODE (427) 7-speed automatic transmission",
  "",
  "");

diagramA["PE27.19-U-2102KA"] = new diagramItem("Electronic selector module control module",
  "TRANSMISSION 722.6 in MODEL 230 up to 08/31/03 with CODE (423) Automatic five-speed transmission (NAG)",
  "",
  "");

diagramA["PE27.19-U-2102KB"] = new diagramItem("Electronic selector module control module",
  "TRANSMISSION 722.6 /9 in MODEL 230 as of 09/01/03<BR>with CODE (423) Automatic five-speed transmission (NAG)<BR>with CODE (427) 7-speed automatic transmission",
  "",
  "");

// 6
groupA["27"] = new groupItem("Automatic Transmission", diagramA);
var diagramA = new Array();

diagramA["PE30.30-U-2050KA"] = new diagramItem("Electrical function diagram for Distronic (DTR)",
  "ENGINE 113.963 /992, 275.951 up to 02/28/06 in MODEL 230 with CODE (219) Distronic (DTR)",
  "",
  "");

diagramA["PE30.30-U-2050KB"] = new diagramItem("Electrical function diagram for Distronic (DTR)",
  "ENGINE 113.995, 273, 275.954 as of 03/01/06 in MODEL 230 with CODE (487) Active Body Control (ABC)",
  "",
  "");

diagramA["PE30.30-U-2051KA"] = new diagramItem("Electrical function diagram for cruise control (CC)",
  "ENGINE 113.963 /992, 275.951 up to 02/28/06 in MODEL 230",
  "",
  "");

diagramA["PE30.30-U-2051KB"] = new diagramItem("Electrical function diagram for cruise control (CC)",
  "ENGINE 113.995, 275.954, 273 as of 03/01/06 in MODEL 230",
  "",
  "");

diagramA["PE30.30-U-2101KA"] = new diagramItem("Distronic (DTR), control module",
  "ENGINE 113.963 /992, 275.951 up to 05/31/04 in MODEL 230 with CODE (219) Distronic (DTR)<BR>Control module N63/1",
  "",
  "");

diagramA["PE30.30-U-2101KB"] = new diagramItem("Distronic (DTR), control module",
  "ENGINE 113.963 /992, 275.951 as of 06/01/04 up to 02/28/06, <BR>113.995, 273, 275.954 as of 03/01/06<BR>in MODEL 230 with CODE (219) Distronic (DTR)<BR>Control module A89",
  "",
  "");

// 6
groupA["30"] = new groupItem("Accelerator Control", diagramA);
var diagramA = new Array();

diagramA["PE32.50-U-2050KA"] = new diagramItem("Electrical function diagram for Active Body Control (ABC)",
  "MODEL 230 up to 02/28/06 with CODE (487) Active Body Control (ABC)",
  "",
  "");

diagramA["PE32.50-U-2050KB"] = new diagramItem("Electrical function diagram for Active Body Control (ABC)",
  "MODEL 230 as of 03/01/06 with CODE (487) Active Body Control (ABC)",
  "",
  "");

diagramA["PE32.50-U-2101KA"] = new diagramItem("Active body control (ABC), control module",
  "MODEL 230 up to 02/28/06 with CODE (487) Active Body Control (ABC)",
  "",
  "");

diagramA["PE32.50-U-2101KB"] = new diagramItem("Active body control (ABC), control module",
  "MODEL 230 as of 03/01/06 with CODE (487) Active Body Control (ABC)",
  "",
  "");

// 4
groupA["32"] = new groupItem("Suspension", diagramA);
var diagramA = new Array();

diagramA["PE40.15-U-2050KA"] = new diagramItem("Function diagram of electrical system of tire pressure monitor",
  "MODEL 230 up to 02/28/06 with CODE (475) Tire pressure monitor (Beru)",
  "",
  "");

diagramA["PE40.15-U-2050KB"] = new diagramItem("Function diagram of electrical system of tire pressure monitor",
  "MODEL 230 as of 03/01/06 with CODE (475) Tire pressure monitor (Beru)",
  "",
  "");

diagramA["PE40.15-U-2101KA"] = new diagramItem("Tire pressure control module",
  "MODEL 230 up to 05/31/05 with CODE (475) Tire pressure monitor",
  "",
  "");

diagramA["PE40.15-U-2101KB"] = new diagramItem("Tire pressure control module",
  "MODEL 230 as of 06/01/05 with CODE (475) Tire pressure monitor",
  "",
  "");

// 4
groupA["40"] = new groupItem("Tire and Wheels", diagramA);
var diagramA = new Array();

diagramA["PE42.45-U-2050KA"] = new diagramItem("Function diagram for electrical system of Electronic Stability Program (ESP)",
  "MODEL 230 up to 02/28/06 with CODE (472) Electronic Stability Program (ESP)",
  "",
  "");

diagramA["PE42.45-U-2050KB"] = new diagramItem("Function diagram for electrical system of Electronic Stability Program (ESP)",
  "MODEL 230 as of 03/01/06 with CODE (472) Electronic Stability Program (ESP)",
  "",
  "");

diagramA["PE42.45-U-2101KA"] = new diagramItem("Electronic stability program (ESP), control module",
  "MODEL 230 up to 02/28/06 with CODE (472) Electronic Stability Program (ESP)",
  "",
  "");

diagramA["PE42.45-U-2101KB"] = new diagramItem("Electronic stability program (ESP), control module",
  "MODEL 230 as of 03/01/06 with CODE (472) Electronic Stability Program (ESP)",
  "",
  "");

// 4
groupA["42"] = new groupItem("Brakes", diagramA);
var diagramA = new Array();

diagramA["PE46.10-U-2101KA"] = new diagramItem("Steering column module, control module",
  "MODEL 230 up to 08/31/03",
  "",
  "");

diagramA["PE46.10-U-2101KB"] = new diagramItem("Steering column module control module",
  "MODEL 230 as of 09/01/03",
  "",
  "");

diagramA["PE46.11-U-2050KA"] = new diagramItem("Function diagram of electrical system for steering wheel heater",
  "MODEL 230",
  "",
  "");

diagramA["PE46.15-U-2050KA"] = new diagramItem("Function diagram of electrical system for steering column adjustment",
  "MODEL 230<BR>Steering column adjustment with memory",
  "",
  "");

// 4
groupA["46"] = new groupItem("Steering", diagramA);
var diagramA = new Array();

diagramA["PE47.20-U-2050KA"] = new diagramItem("Electrical function diagram for fuel pump",
  "ENGINE 113.963 /992, 275.951 up to 02/28/06, <BR>275.981, <BR>113.995, 275.954 as of 03/01/06<BR>in MODEL 230",
  "",
  "");

// 1
groupA["47"] = new groupItem("Fuel System", diagramA);
var diagramA = new Array();

diagramA["PE54.10-U-2101KA"] = new diagramItem("Vehicle electrical system control module",
  "MODEL 230 up to 08/31/03<BR>Control module N82/1, Fusebox F33, F52",
  "",
  "");

diagramA["PE54.10-U-2101KB"] = new diagramItem("Vehicle electrical system control module",
  "MODEL 230 as of 09/01/03<BR>Fusebox F32, <BR>sheet 1",
  "",
  "");

diagramA["PE54.10-U-2101KC"] = new diagramItem("Vehicle electrical system control module",
  "MODEL 230 as of 09/01/03<BR>Control module N82/1, Fusebox F33, F52, <BR>sheet 2",
  "",
  "");

diagramA["PE54.15-U-2103KA"] = new diagramItem("Rear fuse and relay box",
  "MODEL 230<BR>with ENGINE 112.973, 113.963 /992 up to 02/28/06, <BR>113.995 as of 03/01/06",
  "",
  "");

diagramA["PE54.15-U-2103KB"] = new diagramItem("Rear fuse and relay box",
  "MODEL 230<BR>with ENGINE 275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981",
  "",
  "");

diagramA["PE54.15-U-2103KC"] = new diagramItem("Rear fuse and relay box",
  "MODEL 230 with ENGINE 273 as of 03/01/06",
  "",
  "");

diagramA["PE54.15-U-2104KA"] = new diagramItem("Driver-side fuse and relay box",
  "MODEL 230",
  "",
  "");

diagramA["PE54.15-U-2105KA"] = new diagramItem("Passenger-side fuse and relay box",
  "MODEL 230<BR>with ENGINE 113.992 up to 05/31/02, <BR>113.963 up to 02/28/06",
  "",
  "");

diagramA["PE54.15-U-2105KB"] = new diagramItem("Passenger-side fuse and relay box",
  "MODEL 230<BR>with ENGINE 113.992 as of 06/01/02 up to 02/28/06, <BR>113.995 as of 03/01/06<BR>AMG",
  "",
  "");

diagramA["PE54.15-U-2105KC"] = new diagramItem("Passenger-side fuse and relay box",
  "MODEL 230<BR>with ENGINE 275.951 up to 02/28/06, <BR>275.954 as of 03/01/06, <BR>275.981",
  "",
  "");

diagramA["PE54.15-U-2105KD"] = new diagramItem("Passenger-side fuse and relay box",
  "MODEL 230 with ENGINE 273 as of 03/01/06",
  "",
  "");

diagramA["PE54.18-U-2100KA"] = new diagramItem("Voltage distributor",
  "MODEL 230<BR>Z3/29z1, Z3/29z2, Z4/3, Z4/4, Z4/7, Z6/33z2, <BR>Sheet 1",
  "",
  "");

diagramA["PE54.18-U-2100KB"] = new diagramItem("Voltage distributor",
  "MODEL 230<BR>Z7/35, Z7/35z1, Z7/35z2, Z7/35z3, Z7/36, Z7/38, Z7/38z1, Z7/38z2, Z7/39, Z7/41, Z7/43z1, Z7/43z2, <BR>Sheet 2",
  "",
  "");

diagramA["PE54.18-U-2300KA"] = new diagramItem("Connector separation points",
  "MODEL 230<BR>X8/4, X18/32, X30/12, X35/63, X39/29, <BR>sheet 1",
  "",
  "");

diagramA["PE54.18-U-2300KB"] = new diagramItem("Connector separation points",
  "MODEL 230<BR>X35/15, X62/1, X62/2, <BR>sheet 2",
  "",
  "");

diagramA["PE54.21-U-2103KA"] = new diagramItem("Rear signal acquisition and actuation module (SAM) control module",
  "MODEL 230",
  "",
  "");

diagramA["PE54.21-U-2104KA"] = new diagramItem("Electronic ignition switch (EIS) control module",
  "MODEL 230",
  "",
  "");

diagramA["PE54.21-U-2107KA"] = new diagramItem("Overhead control panel (OCP) control module",
  "MODEL 230",
  "",
  "");

diagramA["PE54.21-U-2120KA"] = new diagramItem("Lower control panel control module (N72)",
  "MODEL 230",
  "",
  "");

diagramA["PE54.21-U-2121KA"] = new diagramItem("Driver-side signal acquisition and actuation module (SAM) control module",
  "MODEL 230",
  "",
  "");

diagramA["PE54.21-U-2122KA"] = new diagramItem("Passenger-side signal acquisition and actuation module (SAM) control module",
  "MODEL 230",
  "",
  "");

diagramA["PE54.21-U-2123KA"] = new diagramItem("System diagnosis control module",
  "MODEL 230 up to 08/31/03",
  "",
  "");

diagramA["PE54.21-U-2124KA"] = new diagramItem("Central gateway control module",
  "MODEL 230 as of 09/01/03",
  "",
  "");

diagramA["PE54.22-U-2000KA"] = new diagramItem("Datalink connector/diagnostic socket",
  "MODEL 230 up to 05/31/04",
  "",
  "");

diagramA["PE54.22-U-2000KB"] = new diagramItem("Datalink connector/diagnostic socket",
  "MODEL 230 as of 06/01/04",
  "",
  "");

diagramA["PE54.30-U-2051KA"] = new diagramItem("Function diagram of instrument cluster (IC) electrical system",
  "MODEL 230 up to 02/28/06",
  "",
  "");

diagramA["PE54.30-U-2051KB"] = new diagramItem("Function diagram of instrument cluster (IC) electrical system",
  "MODEL 230 as of 03/01/06",
  "",
  "");

diagramA["PE54.30-U-2101KA"] = new diagramItem("Instrument cluster (IC), control module",
  "MODEL 230",
  "",
  "");

diagramA["PE54.35-U-2050KA"] = new diagramItem("Function diagram of fanfare horn system (FAN) electrical system",
  "MODEL 230",
  "",
  "");

diagramA["PE54.50-U-2050KA"] = new diagramItem("Function diagram of electrical system of trip computer",
  "MODEL 230",
  "",
  "");

diagramA["PE54.65-U-2050KA"] = new diagramItem("Function diagram of Parktronic system (PTS) electrical system",
  "MODEL 230 up to 02/28/06 with CODE (220) Parktronic system (PTS)",
  "",
  "");

diagramA["PE54.65-U-2050KB"] = new diagramItem("Function diagram of Parktronic system (PTS) electrical system",
  "MODEL 230 as of 03/01/06 with CODE (220) Parktronic system (PTS)",
  "",
  "");

diagramA["PE54.65-U-2101KA"] = new diagramItem("Parktronic system (PTS), control module",
  "MODEL 230 up to 02/28/06 with CODE (220) Parktronic system (PTS)",
  "",
  "");

diagramA["PE54.65-U-2101KB"] = new diagramItem("Parktronic system (PTS), control module",
  "MODEL 230 as of 03/01/06 with CODE (220) Parktronic system (PTS)",
  "",
  "");

// 34
groupA["54"] = new groupItem("Electrical Systems - Equipment and Instruments", diagramA);
var diagramA = new Array();

diagramA["PE67.29-U-2050KA"] = new diagramItem("Function schematic for heated rear window electrical system",
  "MODEL 230",
  "",
  "");

// 1
groupA["67"] = new groupItem("Windows", diagramA);
var diagramA = new Array();

diagramA["PE68.05-U-2050KA"] = new diagramItem("Function diagram of electrical system of garage door opener",
  "MODEL 230 with CODE (231) Garage door opener",
  "",
  "");

diagramA["PE68.49-U-2050KA"] = new diagramItem("Function diagram of electrical system of automatic inside rearview mirror dimming",
  "MODEL 230",
  "",
  "");

// 2
groupA["68"] = new groupItem("Interior Equipment", diagramA);
var diagramA = new Array();

diagramA["PE72.29-U-2050KA"] = new diagramItem("Function schematic for power window electrical system",
  "MODEL 230",
  "",
  "");

diagramA["PE72.29-U-2101KA"] = new diagramItem("Door control module (DCM) front left",
  "MODEL 230",
  "",
  "");

diagramA["PE72.29-U-2102KA"] = new diagramItem("Door control module (DCM) front right",
  "MODEL 230",
  "",
  "");

// 3
groupA["72"] = new groupItem("Doors", diagramA);
var diagramA = new Array();

diagramA["PE77.39-U-2050KA"] = new diagramItem("Function schematic for Vario roof electrical system",
  "MODEL 230<BR>without trunk closing assist",
  "",
  "");

diagramA["PE77.39-U-2050KB"] = new diagramItem("Function schematic for Vario roof electrical system",
  "MODEL 230 as of 03/01/06 with CODE (881) Remote trunk closing (RTC [HDFS])<BR>with trunk closing assist",
  "",
  "");

diagramA["PE77.39-U-2101KA"] = new diagramItem("Vario roof, control module",
  "MODEL 230 up to 08/31/03",
  "",
  "");

diagramA["PE77.39-U-2101KB"] = new diagramItem("Vario roof, control module",
  "MODEL 230 as of 09/01/03<BR>without trunk closing assist",
  "",
  "");

diagramA["PE77.39-U-2101KC"] = new diagramItem("Vario roof, control module",
  "MODEL 230 as of 03/01/06 with CODE (881) Remote trunk closing (RTC [HDFS])",
  "",
  "");

// 5
groupA["77"] = new groupItem("Roof - Sliding, Soft/Hard Top, Vario Roof, Attachments", diagramA);
var diagramA = new Array();

diagramA["PE80.20-U-2050KA"] = new diagramItem("Function schematic for central locking (CL) electrical system",
  "MODEL 230",
  "",
  "");

diagramA["PE80.20-U-2101KA"] = new diagramItem("Pneumatic system equipment (PSE)",
  "MODEL 230",
  "",
  "");

diagramA["PE80.40-U-2050KA"] = new diagramItem("Electrical function diagram for power closing",
  "MODEL 230",
  "",
  "");

diagramA["PE80.45-U-2050KA"] = new diagramItem("Function schematic for convenience closing system electrical system",
  "MODEL 230",
  "",
  "");

diagramA["PE80.50-U-2050KA"] = new diagramItem("Function schematic for anti-theft alarm (ATA) electrical system",
  "MODEL 230",
  "",
  "");

diagramA["PE80.50-U-2051KA"] = new diagramItem("Function schematic for panic alarm electrical system",
  "MODEL 230",
  "",
  "");

diagramA["PE80.57-U-2050KA"] = new diagramItem("Function schematic for drive authorization system (DAS) electrical system",
  "MODEL 230",
  "",
  "");

diagramA["PE80.61-U-2101KA"] = new diagramItem("Keyless Go, control module",
  "MODEL 230 up to 02/28/06 with CODE (889) Keyless Go",
  "",
  "");

diagramA["PE80.61-U-2101KB"] = new diagramItem("Keyless Go, control module",
  "MODEL 230 as of 03/01/06 with CODE (889) Keyless Go",
  "",
  "");

// 9
groupA["80"] = new groupItem("Central Locking", diagramA);
var diagramA = new Array();

diagramA["PE82.00-U-2700KA"] = new diagramItem("D2B bus",
  "MODEL 230 up to 05/31/04",
  "",
  "");

diagramA["PE82.00-U-2710KA"] = new diagramItem("MOST bus",
  "MODEL 230 as of 06/01/04",
  "",
  "");

diagramA["PE82.10-U-2051KA"] = new diagramItem("Electrical system function diagram for exterior lights",
  "MODEL 230<BR>Low beam, high beam, daytime running lamps",
  "",
  "");

diagramA["PE82.10-U-2051KB"] = new diagramItem("Electrical system function diagram for exterior lights",
  "MODEL 230<BR>Turn signal lamp, hazard flasher",
  "",
  "");

diagramA["PE82.10-U-2051KC"] = new diagramItem("Electrical system function diagram for exterior lights",
  "MODEL 230<BR>Standing lamps, parking lamps, license plate lamps",
  "",
  "");

diagramA["PE82.10-U-2051KD"] = new diagramItem("Electrical system function diagram for exterior lights",
  "MODEL 230<BR>Front fog lamps, rear fog lamps, backup lamps",
  "",
  "");

diagramA["PE82.15-U-2050KA"] = new diagramItem("Electrical system function diagram for headlamp cleaning system (HCS)",
  "MODEL 230 with CODE (600) Headlamp cleaning system",
  "",
  "");

diagramA["PE82.20-U-2050KA"] = new diagramItem("Electrical system function diagram for interior lights",
  "MODEL 230<BR>Footwell lamps, entrance and exit lamps",
  "",
  "");

diagramA["PE82.30-U-2050KA"] = new diagramItem("Electrical system function diagram for windshield wiper",
  "MODEL 230",
  "",
  "");

diagramA["PE82.60-U-2102KA"] = new diagramItem("Audio gateway, control module",
  "MODEL 230 as of 06/01/04",
  "",
  "");

diagramA["PE82.60-U-2301KA"] = new diagramItem("Satellite digital audio radio (SDAR) system control unit",
  "MODEL 230 up to 05/31/04",
  "",
  "");

diagramA["PE82.60-U-2301KB"] = new diagramItem("Satellite digital audio radio (SDAR) system control unit",
  "MODEL 230 as of 06/01/04",
  "",
  "");

diagramA["PE82.62-U-2101KA"] = new diagramItem("Sound amplifier, control module",
  "MODEL 230 up to 05/31/04 with CODE (810) Sound system",
  "",
  "");

diagramA["PE82.62-U-2101KB"] = new diagramItem("Sound amplifier, control module",
  "MODEL 230 as of 06/01/04 with CODE (810) Sound system",
  "",
  "");

diagramA["PE82.62-U-2103KA"] = new diagramItem("Antenna module",
  "MODEL 230<BR>Sheet 1",
  "",
  "");

diagramA["PE82.62-U-2103KB"] = new diagramItem("Antenna module",
  "MODEL 230<BR>Sheet 2",
  "",
  "");

diagramA["PE82.64-U-2101KA"] = new diagramItem("CD changer (CDC), control module",
  "MODEL 230 up to 05/31/04 with CODE (819) 6-disk CD changer",
  "",
  "");

diagramA["PE82.64-U-2101KB"] = new diagramItem("CD changer (CDC), control module",
  "MODEL 230 as of 06/01/04 with CODE (819) 6-disk CD changer",
  "",
  "");

diagramA["PE82.70-U-2101KB"] = new diagramItem("Cellular phone (CTEL), control module",
  "MODEL 230 up to 05/31/04",
  "",
  "");

diagramA["PE82.70-U-2101KC"] = new diagramItem("Cellular phone (CTEL), control module",
  "MODEL 230 up to 05/31/04 with CODE (387) Preinstallation for telephone &quot;Handy&quot;, UPCI system, USA/Canada",
  "",
  "");

diagramA["PE82.70-U-2101KD"] = new diagramItem("Cellular phone (CTEL), control module",
  "MODEL 230 as of 06/01/04 with CODE (387) Preinstallation for telephone &quot;Handy&quot;, UPCI system, USA/Canada",
  "",
  "");

diagramA["PE82.70-U-2102KA"] = new diagramItem("Voice control system (VCS), control module",
  "MODEL 230 up to 05/31/04 with CODE (813) Voice control system (VCS)",
  "",
  "");

diagramA["PE82.70-U-2102KB"] = new diagramItem("Voice control system (VCS), control module",
  "MODEL 230 as of 06/01/04 with CODE (813) Voice control system (VCS)",
  "",
  "");

diagramA["PE82.85-U-2005KA"] = new diagramItem("Navigation system",
  "MODEL 230 as of 06/01/04",
  "",
  "");

diagramA["PE82.85-U-2101KA"] = new diagramItem("Cockpit management and data system (COMAND), control module",
  "MODEL 230 up to 05/31/04 with CODE (352) COMAND operating and display system",
  "",
  "");

diagramA["PE82.85-U-2101KD"] = new diagramItem("Cockpit management and data system (COMAND), control module",
  "MODEL 230 as of 06/01/04 with CODE (352) COMAND operating and display system",
  "",
  "");

diagramA["PE82.95-U-2101KC"] = new diagramItem("Emergency call system, control module",
  "MODEL 230 up to 05/31/04 with CODE (348) EMERGENCY CALL system",
  "",
  "");

diagramA["PE82.95-U-2101KD"] = new diagramItem("Emergency call system, control module",
  "MODEL 230 as of 06/01/04 with CODE (359) TELE AID emergency call system",
  "",
  "");

// 28
groupA["82"] = new groupItem("Electrical Systems - Body", diagramA);
var diagramA = new Array();

diagramA["PE83.40-U-2050KA"] = new diagramItem("Function diagram, electrics, interior climate control",
  "MODEL 230",
  "",
  "");

diagramA["PE83.40-U-2101KA"] = new diagramItem("Automatic air conditioning (AAC), control module",
  "MODEL 230 with CODE (581) Comfort automatic air conditioning",
  "",
  "");

// 2
groupA["83"] = new groupItem("Heating and Air Conditioning", diagramA);
var diagramA = new Array();

diagramA["PE88.50-U-2050KA"] = new diagramItem("Function diagram of remote trunk opening (RTO)",
  "MODEL 230 up to 02/28/06",
  "",
  "");

diagramA["PE88.50-U-2050KB"] = new diagramItem("Function diagram of remote trunk opening (RTO)",
  "MODEL 230 as of 03/01/06",
  "",
  "");

diagramA["PE88.79-U-2050KA"] = new diagramItem("Function schematic for mirror adjustment electrical system",
  "MODEL 230",
  "",
  "");

// 3
groupA["88"] = new groupItem("Exterior Equipment", diagramA);
var diagramA = new Array();

diagramA["PE91.29-U-2050KA"] = new diagramItem("Function diagram, electrical system, seat adjustment (ESV)",
  "MODEL 230 with CODE (275) Electrically adjustable driver seat, steering column and outside mirrors with memory",
  "",
  "");

diagramA["PE91.29-U-2101KA"] = new diagramItem("Left front seat control module",
  "MODEL 230",
  "",
  "");

diagramA["PE91.29-U-2102KA"] = new diagramItem("Right front seat control module",
  "MODEL 230",
  "",
  "");

diagramA["PE91.30-U-2050KA"] = new diagramItem("Function diagram, electrical system, heated seats (HS)",
  "MODEL 230",
  "",
  "");

diagramA["PE91.59-U-2050KA"] = new diagramItem("Electrical function diagram for roll bar",
  "MODEL 230",
  "",
  "");

diagramA["PE91.60-U-2051KA"] = new diagramItem("Electrical function diagram for airbag",
  "MODEL 230 up to 08/31/03 with CODE (292) Left and right front sidebag",
  "",
  "");

diagramA["PE91.60-U-2051KB"] = new diagramItem("Electrical function diagram for airbag",
  "MODEL 230 as of 09/01/03 with CODE (292) Left and right front sidebag",
  "",
  "");

diagramA["PE91.60-U-2101KA"] = new diagramItem("Airbag control module with integrated emergency call system",
  "MODEL 230 up to 08/31/03 with CODE (292) Left and right front sidebag",
  "",
  "");

diagramA["PE91.60-U-2101KB"] = new diagramItem("Airbag control module with integrated emergency call system",
  "MODEL 230 as of 09/01/03 with CODE (292) Side airbag at front left and right",
  "",
  "");

diagramA["PE91.60-U-2102KA"] = new diagramItem("Weight Sensing System (WSS) control unit",
  "MODEL 230 as of 03/01/06",
  "",
  "");
groupA["91"] = new groupItem("Seats, SRS", diagramA);

// 10

// Total: 154
